### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by fluke777** [dblock/gem-licenses#8]
Hi,

Could we get a new release? I just stumbled upon this little gem and it is pretty sweet. I tried to folow the docs but it seems that the latest released version does not include the Rake task. It was easy to hack around but it would be great to have that provided by the library.

**Comment by dblock** [comment]
It has been a while, cut 0.2.0.

**Comment by fluke777** [comment]
@dblock Weird that my bundler pulled the older version. Sorry for confusion and thanks.

**Comment by dblock** [comment]
I *just* did that. So not weird.
